name: chikitsa
description: Rural healthcare diagnostics app optimized for 2G networks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  protobuf: ^3.1.0
  ffi: ^2.1.0
  zstandard: ^1.3.29 
  fixnum: ^1.1.0
  flutter_image_compress: ^2.4.0
  crypto: ^3.0.7
  uuid: ^4.2.0
  image_picker: ^1.2.1
  # es_compression: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  protoc_plugin: ^21.1.0

dependency_overrides:
  protobuf: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.jpg
    - assets/images/Logo.png
    - assets/patient_dict_32k.zst

